# Generated by Django 4.2.4 on 2023-08-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leads",
            name="is_mail_received",
            field=models.BooleanField(default=False),
        ),
    ]
