# Generated by Django 4.2.4 on 2023-08-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_leads_is_mail_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="lead_id",
            field=models.CharField(max_length=300),
        ),
    ]
