# Generated by Django 4.2.4 on 2023-08-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_alter_leads_lead_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="leads",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
