# Generated by Django 4.2.4 on 2023-09-04 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_leads_create_datetime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leads",
            old_name="user",
            new_name="client",
        ),
    ]
