# Generated by Django 4.2.4 on 2023-09-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("userhandle", "0001_initial"),
        ("leads", "0005_rename_user_leads_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="JornayaUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("pissword", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="client",
            new_name="user",
        ),
        migrations.AddField(
            model_name="leads",
            name="cleint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="userhandle.client",
            ),
        ),
        migrations.CreateModel(
            name="UrlSlug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_slug", models.CharField(max_length=10)),
                ("is_expired", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="userhandle.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaing_id", models.CharField(max_length=100)),
                ("campaign_name", models.CharField(max_length=100)),
                (
                    "jornaya_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="leads.jornayauser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="leads",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="leads.campaign",
            ),
        ),
    ]
