# Generated by Django 4.2.4 on 2023-09-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("unique_id", models.CharField(max_length=100, unique=True)),
                ("cap_limit", models.IntegerField(default=600)),
                ("monthly_payment", models.IntegerField(default=200)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
